---
- name: Create target directory
  file: path={{ item }} state=directory mode=0755
  with_items:
    - "{{ ansible_env.HOME }}/barbican"
    - /var/log/barbican
    - /var/lib/vault/config

- name: Copy docker-compose file to remote
  template:
    src: docker-compose.yaml.j2
    dest: "{{ ansible_env.HOME }}/barbican/docker-compose.yaml"

- name: Copy barbican config files to remote
  template:
    src: etc/barbican/{{ item }}.j2
    dest: /etc/barbican/{{ item }}
  with_items:
    - barbican-api-paste.ini
    - barbican-uwsgi.ini
    - barbican.conf

- name: Copy vault config files to remote
  template:
    src: var/lib/vault/config/config.hcl.j2
    dest: /var/lib/vault/config/config.hcl
  when: barbican_backend == 'vault_plugin'

- name: Run docker-compose up
  docker_service:
    project_src: "{{ ansible_env.HOME }}/barbican/"

# Before this task, all the containers should be running.
- name: Wait for vault unseal and config vault token in barbican config file manually
  local_action: pause
  when: barbican_backend == 'vault_plugin'
  run_once: true

- name: Add barbican-api to haproxy
  debug: msg="TBD"
  when: haproxy_address is defined

- name: Add vault to haproxy
  debug: msg="TBD"
  when: haproxy_address is defined

- name: Initialize barbican database
  shell: docker-compose exec -T barbican sh -c 'barbican-manage db upgrade'
  args:
    chdir: "{{ ansible_env.HOME }}/barbican/"
  run_once: true

- name: Restart barbican service
  shell: docker-compose restart barbican
  args:
    chdir: "{{ ansible_env.HOME }}/barbican/"